### ISSUE TITLE
updates 

### ISSUE THREAD

**Issue by cn-johndpope** [TimoKinnunen/MauiXAMLBluetoothLE#8]
my first hour using visual studio for mac so haven't quite got it figured - but I add some observations.

<img width="1935" alt="Screenshot 2023-03-10 at 5 02 16 pm" src="https://user-images.githubusercontent.com/127367212/224236160-7750e776-26b0-49b6-8666-85674c5dd41b.png">
there seems to be an incompatible package. Is it straightforward to migrate?

communityTookKit.Maui

<img width="671" alt="Screenshot 2023-03-10 at 5 04 38 pm" src="https://user-images.githubusercontent.com/127367212/224236442-79746ae7-b2b5-48bd-a972-92b55046efc3.png">

unbelievabley - it compiles fine from mac to android device on first go.
well done microsoft. 
<img width="2296" alt="Screenshot 2023-03-10 at 5 08 37 pm" src="https://user-images.githubusercontent.com/127367212/224237137-797359c9-c4da-4f25-a686-6d09c9d26c0d.png">

Incompatible packages: 1
Checking compatibility of packages on net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for MauiXAMLBluetoothLE 1.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for CommunityToolkit.Maui 5.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Package CommunityToolkit.Maui 5.0.0 is not compatible with net6.0-maccatalyst16.1 (.NETCoreApp,Version=v6.0) / maccatalyst-x64. Package CommunityToolkit.Maui 5.0.0 supports:
  - net7.0 (.NETCoreApp,Version=v7.0)
  - net7.0-android33.0 (.NETCoreApp,Version=v7.0)
  - net7.0-ios16.1 (.NETCoreApp,Version=v7.0)
  - net7.0-maccatalyst16.1 (.NETCoreApp,Version=v7.0)
  - net7.0-tizen7.0 (.NETCoreApp,Version=v7.0)
  - net7.0-windows10.0.19041 (.NETCoreApp,Version=v7.0)
Checking compatibility for CommunityToolkit.Mvvm 8.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Maui.Dependencies 6.0.552 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Maui.Extensions 6.0.552 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Plugin.BLE 2.2.0-pre5 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for System.Runtime.InteropServices.NFloat.Internal 6.0.1 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Maui.Graphics 6.0.501 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.Configuration 6.0.1 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.DependencyInjection 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.Logging 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.Logging.Abstractions 6.0.1 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.Configuration.Abstractions 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.Primitives 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for System.Runtime.CompilerServices.Unsafe 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for Microsoft.Extensions.Options 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Checking compatibility for System.Diagnostics.DiagnosticSource 6.0.0 with net6.0-maccatalyst16.1 (maccatalyst-x64).
Incompatible packages: 1
Getting restore information for project /Users/johndpope/Documents/gitWorkspace/MauiXAMLBluetoothLE/MauiXAMLBluetoothLE/MauiXAMLBluetoothLE.csproj
Package restore failed. Rolling back package changes for 'MauiXAMLBluetoothLE'.

**Comment by TimoKinnunen** [comment]
I use only pc. And have for development some old iPhone.

**Comment by cn-johndpope** [comment]
When I fix - will post updates.

**Comment by cn-johndpope** [comment]
https://github.com/cn-johndpope/MauiSamples/tree/main/MauiBluetooth
