### ISSUE TITLE
Bluetooth LE permissions not granted

### ISSUE THREAD

**Issue by zmehic** [TimoKinnunen/MauiXAMLBluetoothLE#9]
I've just started the App, no code added, while trying to "Scan nearby devices" and pop-up appears  saying :"Bluetooth LE permissions are not granted". I'm using Xiaomi Mi 11 Lite 5G for debug. Any advice on resolving this problem would help!

**Comment by TimoKinnunen** [comment]
I had Android 13.0 and know that for earlier versions of operating systems on Android asking for permissions is not the same.

**Comment by zmehic** [comment]
Tank you for a quick response, I will surely try on a newer version !
